### ISSUE TITLE
One off my board isn't run

### ISSUE THREAD

**Issue by pierrotm777** [RobTillaart/PCF8575#36]
Hello again Rob,

I have a curious issue with one off my two board.
Several boards exist, a red or a blue.
The blue has a level converter from 5v to 3,3v but i use the pin VDD for the 5V.
The red has no level converter and no pull-up. I have added two 10k resistors.
I use this code for check my two board.
[BURC_16Switchs_Test2.zip](https://github.com/RobTillaart/PCF8575/files/13798789/BURC_16Switchs_Test2.zip)
The blue is running very well but not the red.
The isConnect return me OK for the two boards.
Do you know this difference ?
Thanks for your help.

Pierre

**Comment by RobTillaart** [comment]
Try lower the pull ups to 4k7 or even 2k2.

**Comment by RobTillaart** [comment]
learn all you need to know about i2c and more - https://www.gammon.com.au/i2c

**Comment by pierrotm777** [comment]
Hello Rob,
I have replaced the 10k by 2 4.7k with the same issue.
Now, if i add a pull-up on the P0 pin, this pin is usable as input.
Does exist a way for setup the pins as input with pull-up ?

**Comment by RobTillaart** [comment]
Not that I know, 
The detailed behaviour of the chip is described in the datasheet, furthermore you need to check the schema of your board to understand how the chip is used. That can be different per board.

**Comment by RobTillaart** [comment]
Any progress to report?

**Comment by pierrotm777** [comment]
Hello Rob,

Yes, i have found that my pcf8575 red board is a PCF8575C version.
In input mode, it need 16 pull-up and that solve my issue with this component.
Without pull-up, the input are always set to a low state.

Thanks again for your help:-)

And I wish you a Happy New Year 2024.

Pierre

**Comment by RobTillaart** [comment]
Thanks for reporting back,
That is a good insight to start the new year!   
I'll make a not of it in the readme file so it will pop up in a next release (not planned).

> And I wish you a Happy New Year 2024.

Same to you!

**Comment by RobTillaart** [comment]
Q: do you have a link to a datasheet of the PCF8575C ?
found only an old one from 1999 Philips

**Comment by pierrotm777** [comment]
No sorry.
I have just find some links about pcf857c witch need pull-up.

**Comment by munkerench** [comment]
Oddly found the data sheet here https://www.nxp.com/docs/en/data-sheet/PCF8575C.pdf

**Comment by pierrotm777** [comment]
Thank you for your find

**Comment by RobTillaart** [comment]
Added the datasheets PCF8575 and PCF8575C to this repo
