### ISSUE TITLE
read16() is in Interrupt-Routine not possible 

### ISSUE THREAD

**Issue by Torsten61** [RobTillaart/PCF8575#39]
I wanted to cache/latch the current inputs in an array, because of the slow computer program in the Interrupt call.  
Later, the data should be processed in the slow program one after the other (FIFO).

BUT:  Unfortunately, read16() does not run in the IR-routine....

Suggested solutions?

**Comment by RobTillaart** [comment]
Thanks for the question.
What board are you using?

**Comment by Torsten61** [comment]
Arduino Mega2560 with RS485 and 30 IOs--Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 10.02.24, 21:39 schrieb Rob Tillaart ***@***.***>:

   
  Thanks for the question. What board are you using?

**Comment by RobTillaart** [comment]
Same advice as in your previous question - https://github.com/RobTillaart/PCF8574/issues/50
You need a chip with an input latch to solve this.


Given you have a Mega,  don't you have still some free pins?
If you monitor all input with on board pins you could use a pin change interrupt library. 
Output lines might be moved to PCF8575.
Don't know your requirements so I can only guess if a redesign would help.

**Comment by RobTillaart** [comment]
This library has no solution for it as far as I know.

**Comment by Torsten61** [comment]
So I have to use another HW or optimize the prog-code and use IQR-FLags - Thanks for help!
