### ISSUE TITLE
Sample code error.

### ISSUE THREAD

**Issue by JohnEvans6** [RobTillaart/PCF8575#41]
Please be advised that file PCF8575_array.ino has a fault – using the code “for (uint8_t port = 0; port < 15; port++)” means that the highest port never gets activated. The code should read either “for (uint8_t port = 0; port <= 15; port++)” or “for (uint8_t port = 0; port < 16; port++)”.

Apart from that - thank you for being an excellent source.

**Comment by RobTillaart** [comment]
Thanks for reporting, will adjust it in the next release.

Appreciated!

**Comment by RobTillaart** [comment]
@JohnEvans6 
Created a PR to fix this in all examples (+ some minor edits)
The PR will close this issue when merged.
